name: live-comment
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 30s
      retries: 3
